allowBuilds:
  '@alanscodelog/eslint-config': false
  '@alanscodelog/tsconfigs': false
  core-js: false
  esbuild: true
  unrs-resolver: false
catalog:
  '@types/wicg-file-system-access': ^2023.10.7
strictPeerDependencies: false
